# Generated by Django 3.2.2 on 2021-05-22 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudadano',
            fields=[
                ('idCiudadano', models.AutoField(primary_key=True, serialize=False)),
                ('cuil', models.CharField(max_length=45)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('nroDoc', models.CharField(max_length=45)),
                ('nroTramite', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('extranjero', models.CharField(max_length=45)),
                ('sexo', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('idDomicilio', models.AutoField(primary_key=True, serialize=False)),
                ('idProvincia', models.CharField(max_length=45)),
                ('idDepartamento', models.CharField(max_length=45)),
                ('idLocalidad', models.CharField(max_length=45)),
                ('calle', models.CharField(max_length=45)),
                ('nro', models.CharField(max_length=45)),
                ('piso', models.CharField(max_length=45)),
                ('depto', models.CharField(max_length=45)),
                ('latLocalidad', models.CharField(max_length=45)),
                ('longLocalidad', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('idEvento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('codigoPermiso', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('ciudadano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permisosturismo.ciudadano')),
                ('domicilio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permisosturismo.domicilio')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permisosturismo.evento')),
            ],
        ),
    ]
