# Generated by Django 3.2.3 on 2021-05-23 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisosturismo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permiso',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
