# Generated by Django 3.2.3 on 2021-05-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisosturismo', '0002_alter_permiso_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudadano',
            name='cuil',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
