# Generated by Django 3.2.3 on 2021-05-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisosturismo', '0003_alter_ciudadano_cuil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudadano',
            name='email',
            field=models.EmailField(max_length=45),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='nroDoc',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
