# Generated by Django 3.2.3 on 2021-05-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisosturismo', '0006_alter_ciudadano_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domicilio',
            name='calle',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='depto',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='nro',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='piso',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
