# Generated by Django 3.2.3 on 2021-05-27 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisosturismo', '0007_auto_20210525_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudadano',
            name='email',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='telefono',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='calle',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='depto',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='nro',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='piso',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
